spring.application.name=devmatch

# Application server port
server.port=8080

# Neo4j / CognoDB Connection Properties
# We use Spring environment variable resolution to avoid committing secrets.
neo4j.uri=bolt+s://db-8cd12641.databases.cognodb.com:7687
neo4j.username=cognodb
neo4j.password=8c7a8a4d04dd5c5cdf1c65769ba8b9ce
